import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/context/todo.context";
import { CategoryProvider } from "@/context/category.context";
import { AntdAppProvider } from "@/component/AntdAppProvider";
import { AuthProvider } from "@/context/auth.context";
import { TaskProvider } from "@/context/task.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AntdAppProvider>
          <AuthProvider>
            <CategoryProvider>
              <TodoProvider>
                <TaskProvider>{children}</TaskProvider>
              </TodoProvider>
            </CategoryProvider>
          </AuthProvider>
        </AntdAppProvider>
      </body>
    </html>
  );
}
